#! /usr/bin/env bash

UUIDS="${@}"
ALL_FOUND=0

if [ -z "${UUIDS}" ]
then
  printf "Error: This script requires one or more UUID arguments\n" >&2
  exit 2
fi

for UUID in "${@}"
do

  if ! lsblk -o UUID -lpn | grep -q "${UUID}"
  then
    printf "Error: Failed to find block device with file system UUID=%s\n" ${UUID} >&2
    ALL_FOUND=1
  else
    printf "Found Block Device ${UUID}.\n"
  fi

done

exit ${ALL_FOUND}
