#! /usr/bin/env bash

set -euf -o pipefail

SCRIPT_DIR=$(cd -- $(dirname -- "${BASH_SOURCE[0]}")>/dev/null && pwd)

UUID="${1}"

if [ -z "${UUID}" ]
then
  >&2 printf "Error: UUID argument required\n"
  exit 2
fi

${SCRIPT_DIR}/check_blk -q "${UUID}"

lsblk -lnp -o name,uuid \
  | grep "${UUID}$" \
  | awk '{print $1}'


