vim.cmd('colorscheme night-owl')
--vim.cmd('highlight LineNr ctermfg=246')
--vim.cmd('highlight ColorColumn ctermbg=236')
--vim.cmd('highlight MatchParen ctermfg=15 ctermbg=25')
--vim.cmd('highlight StatusLine ctermbg=251 ctermfg=0')
--vim.cmd('highlight StatusLineNC ctermbg=246 ctermfg=15')
--vim.cmd('highlight NormalNC ctermbg=233')
--vim.cmd('highlight Normal ctermbg=16')
