#!/bin/sh

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Source conf file

[ -r $SCRIPT_DIR/conf ] && source $SCRIPT_DIR/conf

# zramen

zramen make


# Daemonize with pause

exec pause


